# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Feature Branch CI

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use npm v8
        run: npm i -g npm@8.x.x

      - name: Install packages
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Test
        run: npm run test -- --watch=false --browsers=ChromeHeadless
